# Generated by Django 5.0.1 on 2024-05-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='school_type',
        ),
        migrations.AddField(
            model_name='user',
            name='school_group',
            field=models.ManyToManyField(blank=True, null=True, to='authentication.schooltype', verbose_name='school group'),
        ),
        migrations.AlterField(
            model_name='schoolgroup',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='schooltype',
            name='name',
            field=models.CharField(blank=True, max_length=350, verbose_name='Name'),
        ),
    ]
