# Generated by Django 5.0.1 on 2024-05-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_school_type_user_school_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_group',
            field=models.ManyToManyField(blank=True, to='authentication.schooltype', verbose_name='school group'),
        ),
    ]
