# Generated by Django 5.0.1 on 2024-05-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_school_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school_group',
            field=models.ManyToManyField(blank=True, to='authentication.schoolgroup', verbose_name='school group'),
        ),
    ]
