# Generated by Django 5.0.1 on 2024-05-17 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='-', max_length=15, null=True, verbose_name='Number')),
                ('student_name', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='Student name')),
                ('place_of_birth', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='place of birth')),
                ('date_of_birth', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20, verbose_name='Gender')),
                ('level', models.CharField(blank=True, choices=[('LICENCE', 'LICENCE'), ('MAITRISE', 'MAITRISE'), ('DOCTORAT', 'DOCTORAT'), ('BREVET', 'BREVET')], default='LICENCE', max_length=20, verbose_name='level')),
                ('faculty', models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='faculty')),
                ('option', models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='option')),
                ('mention', models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='mention')),
                ('academic_year', models.CharField(blank=True, default='-', max_length=10, null=True, verbose_name='academic year')),
                ('approval_number', models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='approval number')),
                ('folio_number', models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='folio number')),
                ('literal_number', models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='literal number')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='counterpart at')),
                ('sign_at', models.DateTimeField(blank=True, null=True, verbose_name='sign at')),
                ('status', models.CharField(blank=True, choices=[('waiting', 'waiting'), ('approved', 'approved'), ('printed', 'printed'), ('rejected', 'rejected')], default='waiting', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('printed_by', models.DateTimeField(blank=True, null=True, verbose_name='printed at')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approve_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diploma_approve_by', to=settings.AUTH_USER_MODEL, verbose_name='approve by')),
                ('reject_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diploma_reject_by', to=settings.AUTH_USER_MODEL, verbose_name='reject by')),
            ],
            options={
                'verbose_name_plural': 'Diplomas',
                'db_table': 'diplomas',
            },
        ),
        migrations.CreateModel(
            name='DiplomaHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='comment')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diploma_history', to='diploma.diploma', verbose_name='Diploma')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diploma_history_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name_plural': 'Diploma histories',
                'db_table': 'diploma_histories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_payment', models.CharField(max_length=350, verbose_name='Reference payment')),
                ('payment_mode', models.CharField(max_length=350, verbose_name='Payment Mode')),
                ('date_payment', models.DateField(verbose_name='Date Payment')),
                ('amount', models.FloatField(default=0.0, verbose_name='amount')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('proof_of_payment', models.FileField(upload_to='order/proof_of_payment/', verbose_name='proof of payment')),
                ('bedrock_file', models.FileField(upload_to='order/bedrock_file/', verbose_name='bedrock file')),
                ('diploma_file', models.FileField(upload_to='order/diploma_file/', verbose_name='diploma file')),
                ('status', models.CharField(blank=True, choices=[('waiting', 'waiting'), ('approved', 'approved'), ('rejected', 'rejected')], default='waiting', max_length=20, verbose_name='Status')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Rejected at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approve_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_approve_by', to=settings.AUTH_USER_MODEL, verbose_name='approve by')),
                ('order_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_created_by', to=settings.AUTH_USER_MODEL, verbose_name='order by')),
                ('reject_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_reject_by', to=settings.AUTH_USER_MODEL, verbose_name='reject by')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shool_order', to='authentication.school', verbose_name='school order')),
            ],
            options={
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='diploma',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diploma_order', to='diploma.order', verbose_name='diploma order'),
        ),
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='comment')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_history', to='diploma.order', verbose_name='Order')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_history_owner', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name_plural': 'Order histories',
                'db_table': 'order_histories',
            },
        ),
    ]
