# Generated by Django 5.0.1 on 2024-05-18 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_role_user_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(blank=True, max_length=30, verbose_name='Academic year')),
                ('start_date', models.DateTimeField(verbose_name='Start date')),
                ('end_date', models.DateTimeField(verbose_name='End date')),
                ('status', models.CharField(blank=True, choices=[('waiting', 'waiting'), ('open', 'open'), ('close', 'close')], default='waiting', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mission_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name_plural': 'Missions',
                'db_table': 'missions',
            },
        ),
        migrations.CreateModel(
            name='MissionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agents', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Agents')),
                ('configure_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mission_configure_by', to=settings.AUTH_USER_MODEL, verbose_name='configure by')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='school_agent_order', to='authentication.school', verbose_name='school order')),
            ],
            options={
                'verbose_name_plural': 'Mission conf',
                'db_table': 'mission_configurations',
            },
        ),
        migrations.CreateModel(
            name='VerificationQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=30, verbose_name='Question')),
                ('type', models.CharField(blank=True, choices=[('boolean', 'boolean'), ('text', 'text'), ('file', 'file')], default='boolean', max_length=20, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_created_by', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name_plural': 'Verification questions',
                'db_table': 'verification_questions',
            },
        ),
    ]
