# Generated by Django 5.0.1 on 2024-05-18 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0003_alter_verificationquestions_question'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, default='-', max_length=15, null=True, verbose_name='Registration number')),
                ('student_names', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='Student names')),
                ('place_of_birth', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='place of birth')),
                ('date_of_birth', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(blank=True, choices=[('Masculin', 'Masculin'), ('Femini', 'Femini')], default='Masculin', max_length=20, verbose_name='Gender')),
                ('level', models.CharField(blank=True, choices=[('LICENCE', 'LICENCE'), ('MAITRISE', 'MAITRISE'), ('DOCTORAT', 'DOCTORAT'), ('BREVET', 'BREVET')], default='LICENCE', max_length=20, verbose_name='level')),
                ('faculty', models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='faculty')),
                ('option', models.CharField(blank=True, default='-', max_length=256, null=True, verbose_name='option')),
                ('status', models.CharField(blank=True, choices=[('waiting', 'waiting'), ('order', 'order')], default='waiting', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('controller_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalist_controller_by', to=settings.AUTH_USER_MODEL, verbose_name='controller by')),
            ],
            options={
                'verbose_name_plural': 'Finalist',
                'db_table': 'finalists',
            },
        ),
    ]
