# Generated by Django 5.0.1 on 2024-05-18 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schooling', '0005_controller'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalist',
            name='mission_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mission_configurations', to='schooling.missionconfiguration', verbose_name='controller by'),
        ),
    ]
